sudo: required
services:
  - docker


before_install:
  - docker build -t stephengrider/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run stephengrider/react-test npm test -- --coverage

after_success:
  - docker build -t ivanovkirill86/multi-client  ./client
  - docker build -t ivanovkirill86/multi-nginx  ./nginx
  - docker build -t ivanovkirill86/multi-worker  ./worker
  - docker build -t ivanovkirill86/multi-server  ./server
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push ivanovkirill86/multi-client
  - docker push ivanovkirill86/multi-nginx 
  - docker push ivanovkirill86/multi-worker
  - docker push ivanovkirill86/multi-server 




