sudo: required
services:
  - docker

before_install:
  - docker build -t stephengrider/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run stephengrider/react-test npm test -- --coverage

after_success:
  - docker build -t ivanovkirill86/multi-client  ./client
  - docker build -t ivanovkirill86/multi-nginx  ./nginx
  - docker build -t ivanovkirill86/multi-worker  ./worker
  - docker build -t ivanovkirill86/multi-server  ./server
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push ivanovkirill86/multi-client
  - docker push ivanovkirill86/multi-nginx 
  - docker push ivanovkirill86/multi-worker
  - docker push ivanovkirill86/multi-server 

deploy:
  provider: elasticbeanstalk
  region: eu-west-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-1-674028981544
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY